# Generated by Django 3.0.8 on 2020-07-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='filezise',
            new_name='filesize',
        ),
    ]
