# Generated by Django 3.0.8 on 2020-08-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200709_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='section_school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='section_semester',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='section_subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
