# Generated by Django 3.0.8 on 2020-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200805_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
    ]
