# Generated by Django 3.0.8 on 2020-08-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200805_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='video_url',
            field=models.URLField(max_length=100),
        ),
    ]
