# Generated by Django 3.0.8 on 2020-08-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200806_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='section_school',
            field=models.CharField(default='common', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='section_semester',
            field=models.CharField(default='common', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='section_subject',
            field=models.CharField(default='common', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='video_url',
            field=models.URLField(default='NULL', max_length=100),
        ),
    ]
