# Generated by Django 3.0.8 on 2020-08-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20200806_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='num',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='video_url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
