# Generated by Django 3.0.8 on 2020-08-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_remove_board_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('video_title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
