# Generated by Django 3.0.8 on 2020-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='grade',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
