# Generated by Django 3.0.8 on 2020-08-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_board_th_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='th_default',
            new_name='th_high',
        ),
    ]
