# Generated by Django 3.0.8 on 2020-08-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_remove_board_th_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='th_high',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
