# Generated by Django 3.0.8 on 2020-08-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_board_th_high'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='th_default',
            new_name='th_high',
        ),
    ]
