# Generated by Django 3.0.8 on 2020-08-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_auto_20200812_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='th_default',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='th_medium',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
