# Generated by Django 3.0.8 on 2020-08-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20200812_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='th_default',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='th_high',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='th_medium',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='th_default',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='th_medium',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
